-- phpMyAdmin SQL Dump
-- version 4.5.2
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Oct 22, 2017 at 06:10 AM
-- Server version: 5.7.9
-- PHP Version: 5.6.16

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `videogamestore`
--

-- --------------------------------------------------------

--
-- Table structure for table `game`
--

DROP TABLE IF EXISTS `game`;
CREATE TABLE IF NOT EXISTS `game` (
  `game_id` varchar(100) NOT NULL,
  `game_name` varchar(100) NOT NULL,
  `game_description` varchar(10000) NOT NULL,
  `console` varchar(20) NOT NULL,
  `num_players` varchar(20) NOT NULL,
  `coop` varchar(10) NOT NULL,
  `genre` varchar(20) NOT NULL,
  `release_date` date NOT NULL,
  `developer` varchar(50) NOT NULL,
  `publisher` varchar(50) NOT NULL,
  `front_box_art` varchar(50) NOT NULL,
  `back_box_art` varchar(50) NOT NULL,
  `logo` varchar(50) NOT NULL,
  `developer_logo` varchar(50) NOT NULL,
  `price` decimal(20,0) NOT NULL,
  `discount` decimal(20,0) NOT NULL,
  PRIMARY KEY (`game_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `game`
--

INSERT INTO `game` (`game_id`, `game_name`, `game_description`, `console`, `num_players`, `coop`, `genre`, `release_date`, `developer`, `publisher`, `front_box_art`, `back_box_art`, `logo`, `developer_logo`, `price`, `discount`) VALUES
('fea9fe24-b28e-11e7-abc4-cec278b6b50a', 'Nhl 2005', 'The graphics have been even more improved from last year. Now the ''cyber players'' look so close to their real life counterparts that their hard to distinguish. Player models are updated with more life like skin, hair and features. This includes more facial animations and emotions. The coaches are also redone in this manner. The in-game meanwhile adds a whole slew of new animations, cutscenes, goalie animations and enhancements to the fighting engine.\r\n\r\nIn the control department, NHL 2005 adds a new feature called Open-Ice control. This feature lets you potentially control players without the puck, set up for picks, double team and more. Shooting wrist shots and slap shots are also now mapped to separate buttons for more flexibility.\r\n\r\nThe gameplay introduces a new feature as personalities for players. Such that a player like Tie Domi will play more like an enforcer, while Markus Naslund will rely more on finesse and skill. You will be relied on to balance this personalities on each line of a team to create chemistry. The dynasty mode has been redone with a new interface and tweaks. Free Agency and Trading has been tweaked along with the handling of a team. The new system allows you to keep up to date on weekly injuries/streaks reports, letters from you.', 'PlayStation', 'N/A', 'No', 'Sports', '2004-09-22', 'EA Sports', 'EA', 'assets/frontBoxArt/nhl2005.jpg', 'assets/backBoxArt/nhl2005.jpg', 'assets/logo/ea.jpg', 'assets/logo/ea.jpg', '10', '20'),
('5adfeaa4-b2e0-11e7-abc4-cec278b6b50a', 'nba 2k17', 'Following the record-breaking launch of NBA 2K16, the NBA 2K franchise continues to stake its claim as the most authentic sports video game with NBA 2K17. As the franchise that "all sports video games should aspire to be" (GamesRadar), NBA 2K17 will take the game to new heights and continue to blur the lines between video game and reality.', 'Xbox One', '4', 'No', 'Sports', '2016-09-16', 'Visual Concepts', '2k', 'assets/frontBoxArt/nba2k17.jpg', 'assets/backBoxArt/nba2k17.jpg', 'assets/logo/2k.jpg', 'assets/logo/2k.jpg', '45', '0'),
('0a3df864-b2f1-11e7-abc4-cec278b6b50a', 'Fifa 17', 'Powered by Frostbite, FIFA 17 transforms the way you play, compete, and emotionally connect with the game. FIFA 17 immerses you in authentic football experiences by leveraging the sophistication of a new game engine, while introducing you to football players full of depth and emotion, and taking you to brand new worlds accessible only in the game. Complete innovation in the way players think and move, physically interact with opponents, and execute in attack lets you own every moment on the pitch.', 'Xbox One', '1', 'No', 'Sports', '2016-09-27', 'EA Canada', 'Electronic Arts ', 'assets/frontBoxArt/fifa17.jpg', 'assets/backBoxArt/fifa17.jpg', 'assets/logo/ea.jpg', 'assets/logo/ea.jpg', '24', '0'),
('938f826a-b5d8-11e7-abc4-cec278b6b50a', 'Diablo 3', 'The game takes place in Sanctuary, the dark fantasy world of the Diablo series. This world was saved twenty years prior by a handful of unnamed heroes in Diablo II, having survived the onslaught brought by the armies of the Burning Hells, who have gone mad from their ordeals. It is up to a new generation of heroes to face the forces of evil threatening the world of Sanctuary.\r\n\r\nPlayers will have the opportunity to explore familiar settings such as Tristram.\r\n\r\nThe only confirmed NPCs are Deckard Cain, who has appeared in both of the previous games, and his niece, Leah, a new character who accompanies the hero in quests from time to time. The plot will revolve around two surviving Lesser Evils, Azmodan and Belial, and an artifact known as the Black Soulstone. Diablo''s world map is composed primarily of two main continents with several small islands in the Northwest region. The world of Sanctuary has been dramatically changed by the destruction of the World Stone in Diablo II: Lord of Destruction.', 'PlayStation 3', '4', 'Yes', 'ARPG', '2013-03-09', 'Blizzard', 'Activision', 'assets/frontBoxArt/diablo3.jpg', '', 'assets/logo/diablo3.jpg', 'assets/logo/blizzard.jpg', '17', '0'),
('b0a37aa8-b5da-11e7-abc4-cec278b6b50a', 'Marvel vs Capcom 2', 'Marvel vs. Capcom 2: New Age of Heroes is a fighting game, developed and published by Capcom. It is the fourth game in the Marvel vs. Capcom series of fighting games. With the fourth installment of this series, Capcom simplified the player controls to make the gameplay more accessible to the wider audience of casual players. The button configuration was trimmed down to 4 main buttons and 2 assist buttons. The game also features a different air-combo system and 3 on 3 tag, compared to the 2 on 2 tag from previous games in the series.', 'Sega Dreamcast', '2', 'No', 'Fighting', '2000-06-30', 'Capcom', 'Capcom', 'assets/frontBoxArt/mvsc.jpg', 'assets/backBoxArt/mvsc.jpg', 'assets/logo/mvsc.jpg', 'assets/logo/capcom.jpg', '18', '0'),
('97d82bc6-b5db-11e7-abc4-cec278b6b50a', 'The Legend of Zelda:Breath of the Wild', 'The Legend of Zelda: Breath of the Wild is an action-adventure video game developed and published by Nintendo for the Nintendo Switch and Wii U video game consoles. The game is a part of The Legend of Zelda series, and follows amnesiac protagonist Link, who awakens from a hundred-year slumber to a mysterious voice that guides him to defeat Calamity Ganon before he can destroy the kingdom of Hyrule.\r\n\r\nThe title''s gameplay and mechanics constitute a departure from the series'' usual conventions, featuring an open-world environment, a detailed physics engine, high-definition visuals, and voice acting. Announced in 2013, the game was initially planned for release as a Wii U exclusive in 2015, but was delayed twice prior to its release on March 3, 2017. Breath of the Wild was a launch title for the Switch, as well as the final Nintendo-produced game for the Wii U.\r\n\r\nBreath of the Wild received universal acclaim from critics, who deemed it to be one of the greatest video games of all time. Critics praised the game''s open-ended, physics-driven gameplay that encourages player experimentation and exploration, with many calling it a landmark title in open-world game design, although minor criticism was directed at the game''s technical performance at launch.', 'Nintendo Switch', '1', 'No', 'Adventure', '2017-03-03', 'Nintendo', 'Nintendo', 'assets/frontBoxArt/zelda.jpg', 'assets/backBoxArt/zelda.jpg', 'assets/logo/zelda.jpg', 'assets/logo/nintendo.jpg', '80', '0'),
('8929e5a0-b5dc-11e7-abc4-cec278b6b50a', 'Metal Gear Solid HD Collection', 'From the critically acclaimed director, Hideo Kojima, Metal Gear Solid HD Collection offers a handful of the most popular Metal Gear Solid titles from the past in true HD for the first time ever. Featuring three complete games, Metal Gear Solid 2: Sons of Liberty, Metal Gear Solid: Snake Eater and Metal Gear Solid: Peace Walker, the HD Collection offers old and new fans a chance to experience the epic game play, design and storytelling of the MGS franchise. The "Metal Gear Solid (MGS)" series is the seminal work of Hideo Kojima, Japan''s master game creator, and the progenitor of the stealth action game genre. The series has become a global phenomenon, with over 27 million copies sold worldwide. The player controls a secret agent from an elite special forces unit who is sent on solo sneaking missions through enemy installations, vast jungles, and sometimes even the thick of battle. Alone and surrounded by the enemy, even a special forces agent will find it tough to come out alive. But that is the secret behind the series'' popularity-the cerebral challenge of figuring out how to avoid combat, and the thrill of sneaking through enemy territory undetected. The MGS series is also known for its storyline, which blends seamlessly with the gameplay. The scenarios are based on extensive research and incorporate the drama of actual developments in society. These elements have made MGS what it is today: a mature work of entertainment that transcends national borders and the confines of video games, and one of the leading products of the Japanese content business.', 'PlayStation 3', '1', 'No', 'Stealth', '2011-11-08', 'Kojima', 'Konami', 'assets/frontBoxArt/msg.jpg', 'assets/backBoxArt/msg.jpg', 'assets/logo/konami,jpg', 'assets/logo/konami.jpg', '26', '0'),
('e5ff7938-b5dd-11e7-abc4-cec278b6b50a', 'Super Smash Bros : Project M', 'Project M is a community-made mod of Brawl inspired by Super Smash Bros. Melee''s gameplay designed to add rich, technical gameplay to a balanced cast of characters while additionally enhancing the speed of play. Project M employs new codes which seamlessly add in new, universal features to the entire cast to add technical variety to all characters.', 'Nintendo Wii', '1', 'No', 'Fighting', '2014-11-01', 'Project M Development Team', 'Project M Development Team', 'assets/frontBoxArt/pm.jpg', 'assets/backBoxArt/pm.jpg', 'assets/logo/acclaim.jpg', 'assets/logo/acclaim.jpg', '65', '0'),
('3ede9ebc-b5de-11e7-abc4-cec278b6b50a', 'Starcraft 2 : Legacy of the Void', 'You are Hierarch Artanis, leader of the mighty protoss race. Years ago, your homeworld of Aiur fell to the merciless zerg Swarm. Now, at long last, you have raised a powerful fleet of warships known as the Golden Armada, and are poised to reclaim your world. But an ancient evil—Amon—threatens this destiny and the fate of the entire galaxy. Only you can reunite the protoss factions and defeat the coming darkness before it consumes all life in the sector.', 'PC', '4', 'No', 'Strategy', '2015-11-10', 'Blizzard', 'Blizzard', 'assets/frontBoxArt/sc.jpg', 'assets/backBoxArt/sc.jpg', 'assets/logo/blizzard.jpg', 'assets/logo/blizzard.jpg', '56', '0'),
('f660a994-b5df-11e7-abc4-cec278b6b50a', 'Madden 17', 'Take your team all the way in Madden NFL 17 and put yourself at the center of your team’s Championship run in Franchise mode, delivering all-new ways to play and more decisions to make. Driven by the most balanced gameplay yet, the deepest commentary in Madden NFL franchise history, along with fun and fresh ways to play modes such as Ultimate Team and Draft Champions, Madden NFL 17 is the most complete Madden…ever.', 'PlayStation 4', '1', 'No', 'Sports', '2016-08-23', 'EA Tiburon', 'EA Sports', 'assets/frontBoxArt/madden17.jpg', 'assets/backBoxArt/madden17.jpg', 'assets/logo/ea.jpg', 'assets/logo/ea.jpg', '56', '0'),
('884b62d6-b5e0-11e7-abc4-cec278b6b50a\r\n', 'Tales Of Phantasia', '"No overview is currently available for this title."\r\n', 'PlayStation', '1', 'No', 'RPG', '2006-09-07', 'Namco', 'Namco', 'assets/frontBoxArt/tales.jpg', 'assets/backBoxArt/tales.jpg', 'assets/logo/namco.jpg', 'assets/logo/namco.jpg', '30', '0'),
('79daf80a-b5e1-11e7-abc4-cec278b6b50a', 'Monster Hunter', 'The Monster Hunter franchise is a series of fantasy-themed action role-playing video games that started with the game Monster Hunter for PlayStation 2. The series is developed and published by Capcom. As the title suggests, the player takes the role of a hunter in a fantasy environment and completes quests by hunting out specific kinds of monsters to kill or capture. The series has branched out into PlayStation Portable games and a massively multiplayer online game. In Japan, the Monster Hunter series is immensely popular, and it has gained a cult following in the west, with the port Monster Hunter Freedom (known in Japan as Monster Hunter Portable) and its sequels, Monster Hunter Freedom 2 / Monster Hunter Portable 2nd, Monster Hunter Freedom Unite / Monster Hunter Portable 2nd G, Monster Hunter Portable 3rd and an online game called Monster Hunter Frontier Online selling millions of copies, and Monster Hunter Tri becoming the highest-selling third-party Wii game in Japan.[1] Since the series debuted, it has sold 28 million units as of March 31, 2014.[2] As of February 17, 2015, the series has sold 32 million units.[3] There is also an anime based on the spin-off game Monster Hunter Diary: Poka Poka Airou Village and a book called Monster Hunter EPISODE', 'PlayStation 2', '1', 'No', 'ARPG', '2004-09-21', 'Capcom', 'Capcom', 'assets/frontBoxArt/capcom.jpg', 'assets/backBoxArt/capcom.jpg', 'assets/logo/capcom.jpg', 'assets/logo/capcom.jpg', '20', '0'),
('89db0314-b6de-11e7-abc4-cec278b6b50a', 'Halo 3 : ODST', 'Halo 3: ODST ("Orbital Drop Shock Troopers") is a 2009 first-person shooter video game developed by Bungie and published by Microsoft Game Studios. It is part of the Halo franchise, and was released on the Xbox 360 video game console on September 22, 2009. Players assume the roles of United Nations Space Command soldiers, known as "Orbital Drop Shock Troopers" or ODSTs, during and after the events of Halo 2. In the game''s campaign mode, players explore the ruined city of New Mombasa to discover what happened to their missing teammates in the midst of an alien invasion. In the "Firefight" multiplayer option, players battle increasingly difficult waves of enemies to score points and survive as long as possible; Halo 3''s multiplayer is contained on a separate disc packaged with ODST.', 'Xbox One', '4', 'Yes', 'FPS', '2009-09-22', 'Bungie', 'Microsoft Games Studio', 'assets/frontBoxArt/halo3.jpg', 'assets/backBoxArt/halo3.jpg', 'assets/logo/ms.jpg', 'assets/logo/bungie.jpg', '40', '0'),
('a21bec6c-b6df-11e7-abc4-cec278b6b50a', 'Forza 7', 'A racing video game featuring over 700 cars—including new Forza Edition cars, most of which have been brought over from Forza Horizon 3—and more than 200 different configurations to race on across 32 locations at launch, including all from Forza Motorsport 6; a fictional street circuit in Dubai is one of the new circuits and several tracks returning from Forza Motorsport 4 including Maple Valley Raceway, Mugello Circuit and Suzuka Circuit.[4] Two features that are new to the Motorsport title include dynamic weather (previously seen in Horizon titles) and customisable drivers.', 'Xbox One', '1', 'No', 'Racing', '2017-10-03', 'Turn 10 Studios', 'Microsoft Games Studio', 'assets/frontBoxArt/forza7.jpg', 'assets/backBoxArt/forza7.jpg', 'assets/logo/ms.jpg', 'assets/logo/turn.jpg', '80', '0'),
('bbdd1a4e-b6e0-11e7-abc4-cec278b6b50a', 'Overwatch : Origins Edition', 'Overwatch is an upcoming multiplayer first-person shooter in development by Blizzard Entertainment. Unveiled at BlizzCon 2014, the game emphasizes cooperative gameplay using a cast of various "heroes", each with their own abilities and roles within a team. The game entered closed beta in North America and Europe on October 27, 2015, with plans to bring the beta to Asia at a later date. The game is scheduled to be released for Microsoft Windows, PlayStation 4, and Xbox One in the first or second quarter of 2016. Unlike previous Blizzard releases, there are no plans for a version of Overwatch for OS X.', 'PlayStation 4', '4', 'No', 'Shooter', '2016-05-24', 'Blizzard', 'Blizzard', 'assets/frontBoxArt/overwatch.jpg', 'assets/backBoxArt/overwatch.jpg', 'assets/logo/blizzard.jpg', 'assets/logo/blizzard.jpg', '100', '0'),
('277361d2-b6e1-11e7-abc4-cec278b6b50a', 'Grand Theft Auto V', 'Los Santos: a sprawling sun-soaked metropolis full of self-help gurus, starlets and fading celebrities, once the envy of the Western world, now struggling to stay afloat in an era of economic uncertainty and cheap reality TV.\r\n\r\nAmidst the turmoil, three very different criminals plot their own chances of survival and success: Franklin, a street hustler looking for real opportunities and serious money; Michael, a professional ex-con whose retirement is a lot less rosy than he hoped it would be; and Trevor, a violent maniac driven by the chance of a cheap high and the next big score. Running out of options, the crew risks everything in a series of daring and dangerous heists that could set them up for life.\r\n\r\nThe biggest, most dynamic and most diverse open world ever created, Grand Theft Auto V blends storytelling and gameplay in new ways as players repeatedly jump in and out of the lives of the game''s three lead characters, playing all sides of the game''s interwoven story.\r\n\r\nAll the classic hallmarks of the groundbreaking series return, including incredible attention to detail and Grand Theft Auto''s darkly humorous take on modern culture, alongside a brand new and ambitious approach to open world multiplayer.', 'Xbox One', '4', 'No', 'Action', '2014-11-18', 'Rockstar', 'Rockstar', 'assets/frontBoxArt/gta.jpg', 'assets/backBoxArt/gta.jpg', 'assets/logo/gta.jpg', 'assets/logo/rockstar.jpg', '90', '0'),
('c41490ce-b6e1-11e7-abc4-cec278b6b50a', 'Gears of War 4', 'A new generation of soldiers battles the enemy in Gears of War 4, the next game in the blockbuster third-person shooter series.', 'Xbox One', '4', 'Yes', 'Shooter', '2016-10-11', 'The Coalition', 'Microsoft', 'assets/frontBoxArt/gearofwars4.jpg', 'assets/backBoxArt/gearofwars4.jpg', 'assets/logo/bethesda.jpg', 'assets/logo/ms.jpg', '91', '0'),
('991d016a-b6e3-11e7-abc4-cec278b6b50a', 'Ori and the Blind Forest', 'Set as a 2D open world, platform game, the player controls Ori, a white guardian spirit. He has the ability to shoot Spirit Flame and wall run. He is required to interact with his environment as he jump from platforms and solve puzzles. He is faced with enemies as he makes his way to restoring the forest. The player helps Ori collect health shards, energy shards, new abilities, and upgrades. Beside him is Sein who is the light and eyes of the Spirit Tree.', 'PC', '1', 'No', 'Platform', '2015-03-11', 'Moon Studios', 'Microsoft Games Studio', 'assets/frontBoxArt/ori.jpg', 'assets/backBoxArt/ori.jpg', 'assets/logo/moonstudio.jpg', 'assets/logo/ms.jpg', '22', '0'),
('3249dc14-b6e4-11e7-abc4-cec278b6b50a', 'The Witcher 3 : Wild Hunt\r\n', 'The game will be the third in the series, which is based on the book series of the same name by Polish author Andrzej Sapkowski. The Witcher 3 is set "In an open world 30 times larger" than the previous games, featuring the return of protagonist Geralt.\r\n\r\nThe Witcher: Wild Hunt is a story-driven, next-generation open world role-playing game set in a visually stunning fantasy universe full of meaningful choices and impactful consequences. In The Witcher you play as the professional monster hunter, Geralt of Rivia, tasked with finding a child of prophecy in a vast open world rich with merchant cities, viking pirate islands, dangerous mountain passes, and forgotten caverns to explore. \r\n\r\nPLAY AS A HIGHLY TRAINED MONSTER SLAYER FOR HIRE \r\nTrained from early childhood and mutated to gain superhuman skills, strength and reflexes, witchers are a distrusted counterbalance to the monster-infested world in which they live. \r\nGruesomely destroy foes as a professional monster hunter armed with a range of upgradeable weapons, mutating potions and combat magic. \r\nHunt down a wide range of exotic monsters from savage beasts prowling the mountain passes to cunning supernatural predators lurking in the shadows of densely populated towns. \r\nInvest your rewards to upgrade your weaponry and buy custom armour, or spend them away in horse races, card games, fist fighting, and other pleasures the night brings.\r\n\r\nEXPLORE A MORALLY INDIFFERENT FANTASY OPEN WORLD \r\nBuilt for endless adventure, the massive open world of The Witcher sets new standards in terms of size, depth and complexity. \r\nTraverse a fantastical open world: explore forgotten ruins, caves and shipwrecks, trade with merchants and dwarven smiths in cities, and hunt across the open plains, mountains and seas. \r\nDeal with treasonous generals, devious witches and corrupt royalty to provide dark and dangerous services. \r\nMake choices that go beyond good & evil, and face their far-reaching consequences.\r\n\r\nCHASE DOWN THE CHILD OF PROPHECY \r\nTake on the most important contract to track down the child of prophecy, a key to save or destroy this world. \r\nIn times of war, chase down the child of prophecy, a living weapon of power, foretold by ancient elven legends. \r\nStruggle against ferocious rulers, spirits of the wilds and even a threat from beyond the veil – all hell-bent on controlling this world. \r\nDefine your destiny in a world that may not be worth saving.', 'PC', '1', 'No', 'RPG', '2015-05-19', 'CD Projekt Red', 'CD Projekt Red', 'assets/frontBoxArt/witcher3.jpg', 'assets/backBoxArt/witcher3.jpg', 'assets/logo/witcher3.jpg', 'assets/logo/cd.jpg', '90', '0'),
('1e9d1e96-b6e5-11e7-abc4-cec278b6b50a', 'Rise of the Tomb Raider', 'After uncovering an ancient mystery, Lara must explore the most treacherous and remote regions of Siberia to find the secret of immortality before a ruthless organization known as Trinity. Lara must use her wits and survival skills, form new alliances, and ultimately embrace her destiny as the Tomb Raider. Experience high-octane action moments, conquer beautifully hostile environments, engage in brutal guerilla combat, and explore awe-inspiring deadly tombs in the evolution of survival action. In “Rise of the Tomb Raider,” Lara becomes more than a survivor as she embarks on her first Tomb Raiding expedition.', 'PC', '1', 'No', 'Action', '2016-01-28', 'Crystal Dynamics', 'Square Enix', 'assets/frontBoxArt/tombraider.jpg', 'assets/backBoxArt/tombraider.jpg', 'assets/logo/enix.jpg', 'assets/logo/crystal.jpg', '60', '0'),
('f4f4302e-b6e5-11e7-abc4-cec278b6b50a', 'Destiny', 'From the creators of Halo and the publisher of Call of Duty comes Destiny. With an unprecedented variety of FPS gameplay, Destiny promises to deliver an incredible story set within a newly-imagined, always-connected universe filled with action and adventure.\r\n\r\nEverything changed with the arrival of the Traveler. It sparked a Golden Age when our civilization spanned the solar system ... but it didn''t last. Something hit us, knocked us down. The survivors built a city beneath the Traveler, and have begun to explore our old worlds, only to find them filled with deadly foes. In Destiny, you are a Guardian of the last safe city on Earth, able to wield incredible power. Defend the City. Defeat our enemies. Reclaim all that we have lost.', 'PlayStation 4', '4', 'Yes', 'Shooter', '2014-09-09', 'Bungie', 'Activision', 'assets/frontBoxArt/destiny.jpg', 'assets/backBoxArt/destiny.jpg', 'assets/logo/destiny.jpg', 'assets/logo/bungie.jpg', '40', '0'),
('7d15f2d0-b6e6-11e7-abc4-cec278b6b50a', 'Dark Souls 3', 'Prepare to die, again with the third entry in the brutal blockbuster action-RPG franchise. A dark and brooding fantasy adventure awaits players in a vast twisted world full of fearsome beasts, devious traps and hidden secrets. The embers of a once-proud kingdom set the stage for this new adventure. Battle against fearsome enemies and bosses with a variety of weapons and magic through a mysterious land riddled with secrets.', 'PC', '1', 'Yes', 'Action', '2016-04-12', 'FromSoftware', 'Bandai Namco Games', 'assets/frontBoxArt/darksouls.jpg', 'assets/backBoxArt/darksouls.jpg', 'assets/logo/darksouls.jpg', 'assets/logo/bandai.jpg', '40', '0'),
('145ec87e-b6e7-11e7-abc4-cec278b6b50a', 'Battlefield 4', 'Battlefield 4 puts you in the boots of US Marine Sgt. Daniel Recker, member of the Tombstone squad. Against the backdrop of a global conflict between US, Russia and China, you''ll engage in combat on foot and by operating land, sea and air units. \r\n\r\nThankfully, you''re not alone in your struggles on the Battlefield. The bonds with your teammates will grow stronger as you face perils of every kind. Don''t let your squad down; they''re counting on you as much as you need them to survive.\r\n\r\nIn Battlefield 4 you''ll engage in both close quarters squad-based combat and in vast battles commandeering tanks, jeeps, jets, helicopters and naval units. Utilize high-tech gadgets, a wide variety of weapons, and the dynamic environment itself as the climactic story progresses.\r\n\r\nBattlefield 4 takes the fight to many urban environments like the outskirts of Baku and the skyscrapers of Shanghai, all of which become explosive, dynamic playgrounds for the Tombstone Squad.\r\n\r\nWhether you''re riding the waves of the South China Sea or traversing Shanghai''s iconic Huangpu River, naval warfare is central in Battlefield 4''s single player campaign.\r\n\r\nFight on huge fields, massive industrial areas, or in enemy air space. Nothing compares to the scale and scope of Battlefield 4.', 'PC', '4', 'Yes', 'Shooter', '2013-10-31', 'EA Digital Illusions CE', 'EA', 'assets/frontBoxArt/battlefield4.jpg', 'assets/backBoxArt/battlefield4.jpg', 'assets/logo/battlefield4.jpg', 'assets/logo/ea.jpg', '13', '0'),
('a4ea2802-b6e7-11e7-abc4-cec278b6b50a', 'Middle-Earth : Shadow of Mordor', 'Middle-Earth: Shadow of Mordor is an action-packed adventure-RPG inspired by J.R.R. Tolkien''s The Hobbit and The Lord of the Rings. Exploring an original story of vengeance and redemption, the game puts players in the role of Talion, a valiant ranger whose family is slain in front of him the night Sauron and his army return to Mordor -- moments before his own life is taken. Resurrected by a Spirit of vengeance and empowered with Wraith abilities, Talion ventures into Mordor and vows to destroy those who have wronged him. Through the course of his personal vendetta, Talion uncovers the truth of the Spirit that compels him, learns the origins of the Rings of Power and ultimately confronts his true nemesis.', 'PlayStation 4', '1', 'No', 'ARPG', '2014-09-30', 'Monolith Productions', 'Warner Bros. Interactive', 'assets/frontBoxArt/shadow.jpg', 'assets/backBoxArt/shadow.jpg', 'assets/logo/shadow.jpg', 'assets/logo/wb.jpg', '46', '0'),
('7c3d8b00-b6e8-11e7-abc4-cec278b6b50a', 'DOOM', 'Science has unlocked the gates to the unknown, and now the only thing standing in the way of the forces of Hell is a lone space marine. Featuring dramatic storylines, pulse-pounding action, revolutionary technology and unique sci-fi based weaponry, DOOM is the franchise that ushered in the FPS revolution and evolved the genre into the juggernaut it is today. With several installments featuring some of the most frightening and gripping first-person gaming experiences ever created, the DOOM franchise is a cultural milestone that has transcended the realm of video games on the way to becoming a mainstream entertainment phenomenon.', 'Xbox One', '4', 'No', 'Shooter', '2016-05-13', 'ID Software', 'Bethesda', 'assets/frontBoxArt/doom.jpg', 'assets/backBoxArt/doom.jpg', 'assets/logo/id.jpg', 'assets/logo/bethesda.jpg', '80', '0'),
('e9fb828c-b6e8-11e7-abc4-cec278b6b50a', 'Metal Gear Solid V : The Phantom Pain', 'Development powerhouse, Kojima Productions, continues forth the ‘METAL GEAR SOLID V Experience’ with the latest chapter, METAL GEAR SOLID V: The Phantom Pain. Ushering in a new era for the franchise with cutting-edge technology powered by the Fox Engine, MGSV: The Phantom Pain, will provide players a first-rate gaming experience as they are offered tactical freedom to carry out open-world missions.\r\n\r\nTaking place nine years after the events of MGSV: Ground Zeroes and the fall of Mother Base, Snake a.k.a. Big Boss, awakes from a near decade-long coma. The game resumes the story in 1984, with the Cold War still as the backdrop, which continues to shape a global crisis. Snake’s journey takes him into a world where he is driven by a need for revenge and the pursuit of a shadow group, XOF.\r\n\r\nHideo Kojima, head of Kojima Productions, continues to ambitiously explore mature themes such as the psychology of warfare and the atrocities that result from those that engage in its vicious cycle. One of the most anticipated games of the year with its open-world design, photorealistic visual fidelity and feature-rich game design, MGSV: The Phantom Pain will leave its mark as one of the hallmarks in the gaming industry for its cinematic storytelling, heavy themes, and immersive tactical gameplay.', 'PlayStation 4', '1', 'No', 'Stealth', '2015-09-01', 'Kojima', 'Konami', 'assets/frontBoxArt/phantom.jpg', 'assets/backBoxArt/phantom.jpg', 'assets/logo/konami.jpg', 'assets/logo/kojima.jpg', '50', '0'),
('d3969ada-b6e9-11e7-abc4-cec278b6b50a', 'Inside', 'Inside is a 2D puzzle platformer that builds upon what made Limbo great.', 'PC', '1', 'No', 'Platform', '2016-06-29', 'Playdead', 'Playdead', 'assets/frontBoxArt/inside.jpg', 'assets/backBoxArt/inside.jpg', 'assets/logo/playdead.jpg', 'assets/logo/playdead.jpg', '30', '0'),
('63b4199e-b6ea-11e7-abc4-cec278b6b50a', 'Injustice : Gods Among Us', 'What if our greatest heroes became our greatest threat ? Injustice: Gods Among Us debuts as a bold new fighting game franchise that introduces a deep, original story featuring favorite DC Comics icons such as Batman, Superman, Wonder Woman, The Flash, Harley Quinn, Solomon Grundy and others. Set in a world where the lines between good and evil are is blurred, players will experience heroes and villains engaging in epic battles on a massive scale.', 'Nintendo Wii U', '2', 'No', 'Fighting', '2013-04-16', 'NetherRealm Studios', 'Warner Bros', 'assets/frontBoxArt/injustice.jpg', 'assets/backBoxArt/injustice.jpg', 'assets/logo/wb.jpg', 'assets/logo/nether.jpg', '30', '0'),
('e5ecc294-b6ea-11e7-abc4-cec278b6b50a', 'Mario Kart 8 Deluxe', 'Hit the road with the definitive version of Mario Kart 8 and play anytime, anywhere! Race your friends or battle them in a revised battle mode on new and returning battle courses. Play locally in up to 4-player multiplayer in 1080p while playing in TV Mode. Every track from the Wii U version, including DLC, makes a glorious return. Plus, the Inklings appear as all-new guest characters, along with returning favorites, such as King Boo, Dry Bones, and Bowser Jr.!', 'Nintendo Switch', '4', 'Yes', 'Sports', '2017-04-28', 'Nintendo', 'Nintendo', 'assets/frontBoxArt/mariokart.jpg', 'assets/backBoxArt/mariokart.jpg', 'assets/logo/nintendo.jpg', 'assets/logo/nintendo.jpg', '100', '0'),
('51048a26-b6eb-11e7-abc4-cec278b6b50a', 'Mario Party 10', 'Bowser crashes the latest Mario Party, the first installment of the series on the Wii U console. In the new Bowser Party mini-games, play as Bowser himself and face off against up to four others playing as Mario and friends. Control Bowser using the buttons, motion controls and touch screen of the Wii U GamePad controller in different ways, and wreak havoc as Bowser in each mini-game while the other players strive to survive.', 'Nintendo Wii U', '4', 'No', 'Action', '2015-03-20', 'Nintendo', 'Nintendo', 'assets/frontBoxArt/marioparty.jpg', 'assets/backBoxArt/marioparty.jpg', 'assets/logo/marioparty.jpg', 'assets/logo/nintendo.jpg', '40', '0'),
('062fbba0-b6ec-11e7-abc4-cec278b6b50a', 'Metroid Prime', 'Ten years ago, beneath the surface of Planet Zebes, the mercenaries known as "Space Pirates" were defeated by interstellar bounty hunter Samus Aran. Descending to the very core of the pirate stronghold, Samus exterminated the energy based parasites called "Metroids" and defeated Mother Brain, the leader of the pirate hoarde.\r\n\r\nBut the Space Pirates were far from finished. Several pirate research vessels were orbiting Zebes when Samus fought on the surface below.\r\n\r\nAfter the fall of Mother Brain, the ships escaped, with the hope of finding enough resources to rebuild their forces and take their revenge.\r\n\r\nAfter discovering a possible pirate colony on planet Talon IV, Samus has once again prepared for war, hoping to end the Pirate threat forever.', 'Nintendo GameCube', '1', 'No', 'Action', '2002-11-17', 'Retro Studios', 'Nintendo', 'assets/frontBoxArt/metroid.jpg', 'assets/backBoxArt/metroid.jpg', 'assets/logo/metroid.jpg', 'assets/logo/retro.jpg', '14', '0');

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` varchar(100) NOT NULL,
  `password` varchar(20) NOT NULL,
  `firstname` varchar(20) NOT NULL,
  `lastname` varchar(20) NOT NULL,
  `email` varchar(50) NOT NULL,
  `address1` varchar(50) NOT NULL,
  `address2` varchar(50) NOT NULL,
  `city` varchar(40) NOT NULL,
  `state` varchar(40) NOT NULL,
  `zip` varchar(10) NOT NULL,
  `country` varchar(40) NOT NULL,
  `credit_card_type` varchar(20) NOT NULL,
  `credit_card_number` varchar(20) NOT NULL,
  `credit_card_cvv` varchar(10) NOT NULL,
  `credit_card_expiry` varchar(20) NOT NULL,
  `last_login` varchar(20) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `password`, `firstname`, `lastname`, `email`, `address1`, `address2`, `city`, `state`, `zip`, `country`, `credit_card_type`, `credit_card_number`, `credit_card_cvv`, `credit_card_expiry`, `last_login`) VALUES
('d593a994-5fcf-4435-b958-cd57516c1ecd', 'moraza', 'moh', 'raza', 'mr@mo.ca', '990', 'cote', 'Montréal', 'quebec', 'h9b2n2', 'canada', 'master', '1234567891011121', '111', '04/2012', '2017.10.15.22.51.52'),
('2ae4a0ce-6c5f-48b2-a0fd-a1d5f4f903d3', 'jlum1234', 'jason', 'lum', 'j@lum.com', '1234 cote vertu', '', 'Montréal', 'Quebec', 'H4R124', 'Canada', 'visa', '4716689946371157', '260', '02/2020', '2017.10.20.18.17.51');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
